apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-master
  namespace: shortLink
spec:
  selector:
    matchLabels:
      name: master
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        name: master
        version: v1
    spec:
      containers:
      - name: shortLink-master
        image: "{{index .Values.images 0}}:{{.Values.version}}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80