apiVersion: v1
kind: Service
metadata:
  name: k8s-shortLink-server-master
  namespace: shortLink
spec:
  type: NodePort
  selector:
    name: master
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 80 

